name: heyva
description: Mom's Application
publish_to: none
version: 1.0.0+1
environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  get: 4.6.5
  webview_flutter: ^3.0.4
  json_annotation: ^4.6.0
  http: ^0.13.5
  provider: any
  flutter_spinkit: ^5.1.0
  # firebase_core: 1.24.0
  firebase_core: ^2.7.0
  # firebase_auth: 3.11.2
  firebase_auth: ^4.2.9
  bottom_picker: ^2.0.1
  # untuk timer 321
  animated_text_kit: ^4.2.2
  # untuk timer 321
  miniplayer: ^1.0.1
  flutter_riverpod: ^2.3.0
#  timeago: ^3.4.0
  flutter_svg: ^1.1.2
  timelines: ^0.1.0
#  multi_select_item: ^1.0.3 # multiselect list
  story_view: ^0.14.0 # instagram_stories
  persistent_bottom_nav_bar: ^5.0.2 # custom bottom navigation
  lottie: ^2.2.0 # lottie
  # gakepake buat animated splashscreen
  animated_splash_screen: ^1.2.0
  page_transition: ^2.0.9
  # gakepake buat animated splashscreen
  flutter_dash: ^1.0.0
  easy_stepper: ^0.3.2
  carousel_slider: ^4.2.1
  readmore: ^2.2.0
  flutter:
    sdk: flutter
  pull_to_refresh: ^2.0.0
  dio: ^5.0.3
  loading_overlay: ^0.3.0
  get_storage: ^2.1.1
  appinio_video_player: ^1.2.0
  flutter_staggered_grid_view: ^0.6.2

dev_dependencies:
  flutter_lints: 2.0.1
  build_runner: ^2.2.0
  json_serializable: ^6.3.1
  status_change: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/

resources:
  - string.dart
  - color.dart