// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLDhfnx08-emolWs-SYg6xFKalPFwcBdA',
    appId: '1:622669316286:web:5eb8aedd08ddb131b49eef',
    messagingSenderId: '622669316286',
    projectId: 'heyva-151a4',
    authDomain: 'heyva-151a4.firebaseapp.com',
    storageBucket: 'heyva-151a4.appspot.com',
    measurementId: 'G-E8QBPYB4HQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDa1BdCMy3FT6QHpoc2E1NEAdt13pGgwy0',
    appId: '1:622669316286:android:20ddfd75c5d13923b49eef',
    messagingSenderId: '622669316286',
    projectId: 'heyva-151a4',
    storageBucket: 'heyva-151a4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDs9rfny1317KZnK0jOKkQHUrqYfxBtFbk',
    appId: '1:622669316286:ios:115ced4334ba38ddb49eef',
    messagingSenderId: '622669316286',
    projectId: 'heyva-151a4',
    storageBucket: 'heyva-151a4.appspot.com',
    iosClientId: '622669316286-a12nm6lceeqmjtfnl7db2qf5ibc1qtde.apps.googleusercontent.com',
    iosBundleId: 'com.example.heyva',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDs9rfny1317KZnK0jOKkQHUrqYfxBtFbk',
    appId: '1:622669316286:ios:115ced4334ba38ddb49eef',
    messagingSenderId: '622669316286',
    projectId: 'heyva-151a4',
    storageBucket: 'heyva-151a4.appspot.com',
    iosClientId: '622669316286-a12nm6lceeqmjtfnl7db2qf5ibc1qtde.apps.googleusercontent.com',
    iosBundleId: 'com.example.heyva',
  );
}
