// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDoedJmzm4LcBiTwP-SXPw7FNt8ksAen6o',
    appId: '1:159265582817:web:86b1d68141a965cafa51a0',
    messagingSenderId: '159265582817',
    projectId: 'heyva-b10f5',
    authDomain: 'heyva-b10f5.firebaseapp.com',
    storageBucket: 'heyva-b10f5.appspot.com',
    measurementId: 'G-GFNP2ZQDRF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7nq_3tkceIpVVgdQU4fNU4omfO-lXOaM',
    appId: '1:159265582817:android:76475a397e2616ddfa51a0',
    messagingSenderId: '159265582817',
    projectId: 'heyva-b10f5',
    storageBucket: 'heyva-b10f5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3pQdYBR5_e9ODk_bjUR35XacRp_oda64',
    appId: '1:159265582817:ios:fc04596e3713a036fa51a0',
    messagingSenderId: '159265582817',
    projectId: 'heyva-b10f5',
    storageBucket: 'heyva-b10f5.appspot.com',
    iosClientId: '159265582817-fdfn285gh53e1jtrhn6dtmb13q2dsib5.apps.googleusercontent.com',
    iosBundleId: 'com.heyva.health',
  );
}
